---
title: 'ETC3250/5350: Project report'
author: "CHANGE ME: Add your team members names here, and team name"
date: "Jun 7, 2020"
output: 
  html_document
---

## `r emo::ji("llama")` Introduction

Sentence about the data

- what are the variables, 
- what are the observations, and how many

ADD A PICTURE OF SOME SKETCHES

## `r emo::ji("wrench")` Methodology  

Summarise your best model and how you trained your model. This section needs to be understandable by your class members.  

Also include a sentence or two describing the full range of models examined/ 

## `r emo::ji("seedling")` Results and Discussion

This includes for example graphs and tables, as well as a discussion of the results. You should summarise your training error, the important variables. Include at least one plot that is important, ideally of the important variables, or of observations that are consistently misclassified. It could be good to have one interesting fact about the data. 

## `r emo::ji("moon_cake")` Conclusion

Short paragraph about what you have learned from the model, getting to your best model, and about the data . 

##  `r emo::ji("apple")` References

Cite any sources for the modelling

Cite all R packages (or other software) used in the work. 

For example:

Gareth James, Daniela Witten, Trevor Hastie, Robert Tibshirani. (2013). An Introduction to Statistical Learning: with Applications in R. New York :Springer.

Tianqi Chen, Tong He, Michael Benesty, Vadim Khotilovich, Yuan
  Tang, Hyunsu Cho, Kailong Chen, Rory Mitchell, Ignacio Cano,
  Tianyi Zhou, Mu Li, Junyuan Xie, Min Lin, Yifeng Geng and Yutian
  Li (2019). xgboost: Extreme Gradient Boosting. R package version
  0.90.0.2. https://CRAN.R-project.org/package=xgboost
  

**This section does NOT count in the 5 pages**

## `r emo::ji("cricket")` Appendix

Anything else you  would like to include but that are not the most important things. 

**This section does NOT count in the 5 pages**
